---
spellchecker: aspell

matrix:
  - name: Config
    aspell:
      lang: en
      d: en_US
    sources:
      - ./LICENSE
      - '**.md'
      - ./profile
      - ./.github
      - ./.gitlab-ci.yml
      - ./.gitlab-ci.yaml
      - '**.yml'
      - '**.yaml'
      - '**.json'
    default_encoding: utf-8
    pipeline:
      - pyspelling.filters.url:
    dictionary:
      wordlists:
        - .dict-custom.txt
