---
#
# .github/workflows/misspell.yml
#
name: misspell Workflow
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_dispatch:

env:
  REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

defaults:
  run:
    shell: bash

jobs:
  spelling:
    name: Spelling Check
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Run misspell
        uses: reviewdog/action-misspell@v1
        with:
          fail_on_error: true
          level: error
          locale: "US"
          reporter: github-check
