---
#
# .github/workflows/woke.yml
#
name: Woke Workflow
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_dispatch:

env:
  REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

defaults:
  run:
    shell: bash

jobs:
  woke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        id: checkout-repo
        uses: actions/checkout@v4
      - name: woke with reviewdog
        id: woke
        uses: get-woke/woke-action-reviewdog@v0
        with:
          # [github-pr-check, github-check, github-pr-review].
          reporter: github-check
          level: error
          fail-on-error: true
